### ISSUE TITLE
Prefix non-unique IDs

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#19] opened 2016-09-01 02:29 UTC
Hi @cyberbikepunk 

I was checking that if you select Clasificación Administrativa in Hierarchies, Ramo disappears from the available filters, which shouldn't be because Ramo is a useful filter to visualize the treemaps more easily.

Here's the reproduction:

http://next.openspending.org:80/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:mex-restructured?lang=en&measure=Aprobado.sum&groups[]=administrative_classification_2.Ramo&order=Aprobado.sum|desc

**Comment by akariv** [comment] 2016-09-01 06:54
As explained during the last call, this is by design.

Drilling down should be done via the visualisation. When you click on the visualisation, the filters and grouping parameters change together to show meaningful information.

Depending on where you are in the hierarchy, applying a filter from the same hierarchy can only lead to one of these options:
- Nothing changing
- One big box appearing
- No data is seen at all

**Comment by Victordeleon** [comment] 2016-09-02 15:28
@akariv this is an issue related to what we talked during our last call.

Since lower hierarchies ID's are not unique, you need the upper hierarchy filters to discriminate your search.

For example, if I'm looking for "PROSPERA Programa de Inclusión Social", which is Ramo=20, Modalidad del programa presupuestario=S, clave del programa presupuestario = 072, in the Administrative Classification, I won't be able to find it because the Programa Presupuestario gives me different options to select.

![image](https://cloud.githubusercontent.com/assets/17733942/18208937/31aae82c-70f7-11e6-92f6-3c179c13a2c8.png)

If we implemented what was discussed during the last call, meaning that the filters appear and dissapear according to the upper hierarchy selected, having ramo would be pretty useful to discriminate non-unique ID's at the programa presupuestario level.

**Comment by cyberbikepunk** [comment] 2016-09-28 09:57
>  Just as we asked for, Modalidad and Programa Presupuestario were both incorporated to the Administrative Classification. This partially corrects the issue because it solves looking for a Programa Presupuestario at the Tree Maps in the Administrative Classification (which is our default visualization).
> 
> However, as expected, the problem persists if you try to filter Programa Presupuestario in the Functional and Economic Classification.
> 
> For example f I filter Clasificación Funcional by:
> 
> 2.1.                2016 and ID_PP=57 I get the right amount (comparing to the raw data base).http://next.openspending.org:80/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-19?lang=es&measure=Aprobado.sum&groups[]=functional_classification_2.Grupo_Funcional&filters[date_2.Ciclo][]=2016&filters[administrative_classification_5.Programa_Presupuestario][]=57&order=Aprobado.sum|desc
> 
> 2.2.                2016, Modalidad=U and ID_PP=57 I get the right amount (comparing to the raw data base) which in the data base corresponds to Ramo=23, Modalidad=U, ID_PP=57.http://next.openspending.org:80/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-19?lang=es&measure=Aprobado.sum&groups[]=functional_classification_2.Grupo_Funcional&filters[date_2.Ciclo][]=2016&filters[administrative_classification_4.Modalidad_del_Programa][]=U&filters[administrative_classification_5.Programa_Presupuestario][]=57&order=Aprobado.sum|desc
> 
> 2.3.               2016, Modalidad=S and ID_PP=57 I get the right amount (comparing to the raw data base) which in the data base corresponds to Ramo=20, Modalidad=S, ID_PP=57.http://next.openspending.org:80/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-19?lang=es&measure=Aprobado.sum&groups[]=functional_classification_2.Grupo_Funcional&filters[date_2.Ciclo][]=2016&filters[administrative_classification_4.Modalidad_del_Programa][]=S&filters[administrative_classification_5.Programa_Presupuestario][]=57&order=Aprobado.sum|desc
> 
> However, in all cases I get the same filter label: 57-Programas del Fondo Nacional de Fomento a las Artesanías (FONART) which would only be correct for case 2.3, in the other two cases would be wrong information.
> 
> Same thing happens if you try 2016 and ID_PP=72, and then you filter by Ramo 11, 12 or 20. In each case you’ll get the correct amount; however, the filter will be 72 -  Reforma Curricular en Educación Básica (PP description that doesn’t belong to 2016). So is showing wrong information.
> 
> So, this issue is solved only for the default visualization, yet is still needed to find a way in which we can filter ID_PP taking into account their ID’s are not unique.

**Comment by cyberbikepunk** [comment] 2016-09-28 10:02
So @Victordeleon @auramartinez: in the [sample upload iteration #19](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-19?lang=en), I merged the 2 hierarchies but did not prefix the IDs. There was a change of mind after the conference call, and i wasn't clear anymore on whether you needed the prefixing). Let me upload a revised version with IDs prefixed for the administrative category. This is a work-around (as we have already discussed). The long-term solution (partial IDs in the packager) has been prioritized. You can follow it [here](https://github.com/openspending/openspending/issues/1112).

**Comment by cyberbikepunk** [comment] 2016-09-28 14:05
@Victordeleon @auramartinez please check out [the results of pipeline run #20](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-20). This is also a 100,000 sample, but this time I prefixed the IDs in the administrative hierarchy. 

cc @dianaMPG @akariv

**Closed as completed** 2016-11-29 00:08 UTC
Labels: bug, pipeline issue
